// <auto-generated />
using CadastraCaminhao.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CadastraCaminhao.Infra.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("CadastraCaminhao.Domain.Entities.Truck", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("color");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(60)")
                        .HasColumnName("description");

                    b.Property<string>("Image")
                        .HasColumnType("varchar(80)")
                        .HasColumnName("image");

                    b.Property<int>("Model")
                        .HasColumnType("varchar(2)")
                        .HasColumnName("model");

                    b.Property<int>("ModelYear")
                        .HasColumnType("int(4)")
                        .HasColumnName("modelYear");

                    b.Property<int>("YearOfManufacture")
                        .HasColumnType("int(4)")
                        .HasColumnName("yearOfManufacture");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("tabTruck");
                });

            modelBuilder.Entity("CadastraCaminhao.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
